version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 05kickass
      POSTGRES_DB: Blog_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-web
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - ".:/app"
    working_dir: /app
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: postgres://postgres:05kickass@db:5432/Blog_development
    ports:
      - "3000:3000" 
  
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-sidekiq
    command: bundle exec sidekiq
    volumes:
      - ".:/app"
    working_dir: /app
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: postgres://postgres:05kickass@db:5432/Blog_development

volumes:
  db_data:
